# @immonex/doc-gen Konfiguration
# Docs: https://docs.immonex.de/doc-gen
# Source: https://npm.immonex.de/#/detail/@immonex/doc-gen
# Docsify-Konfiguration: https://docsify.js.org/#/configuration

title: Kickstart for Elementor
subtitle: immonex Kickstart for Elementor
description: 35+ Widgets und Dynamic Tags zur Erstellung professioneller Immobilien-Websites mit immonex Kickstart und Elementor
keywords:
  - wordpress
  - plugin
  - immobilien
  - elementor
  - widgets
author: Carsten Scheuer

name: kickstart-for-elementor
permission: public
category: Plugins

subMaxLevel: 2

plugins:
  docsify:
    css: assets/ext-style.css
    js: assets/docsify-plugin-scroll-bug-fix.js